# services:
#   database:
#     image: postgres
#     container_name: database
#     restart: unless-stopped
#     environment:
#       POSTGRES_PASSWORD: secret
#       POSTGRES_DB: everlasting-heaven-suite
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

# Dockerfile
# FROM php:7.2-cli

# RUN apt-get update -y && apt-get install -y libmcrypt-dev

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN docker-php-ext-install pdo mbstring

# WORKDIR /app
# COPY . /app

# RUN composer install

# EXPOSE 8000
# CMD php artisan serve --host=0.0.0.0 --port=8000